package com.busymachines.commons.domain

import com.busymachines.commons.{EnumValue, Enum}

trait Language extends EnumValue[Language]
object Language extends Enum[Language] {
  case class Value(value: Int, name: String) extends Val with NextId with Language
  val AFRIKAANS = Value(1, "af")
  val AMHARIC = Value(2, "am")
  val ARABIC = Value(3, "ar")
  val BELARUSIAN = Value(4, "be")
  val BENGALI = Value(5, "bn")
  val BULGARIAN = Value(6, "bg")
  val BOSNIAN = Value(7, "bs")
  val CATALAN = Value(8, "ca")
  val CZECH = Value(9, "cs")
  val DANISH = Value(10, "da")
  val GERMAN = Value(11, "de")
  val GREEK = Value(12, "el")
  val ENGLISH = Value(13, "en")
  val SPANISH = Value(14, "es")
  val ESTONIAN = Value(15, "et")
  val PERSIAN = Value(16, "fa")
  val FINNISH = Value(17, "fi")
  val FAROESE = Value(18, "fo")
  val FRENCH = Value(19, "fr")
  val GUJARATI = Value(20, "gu")
  val HEBREW = Value(21, "he")
  val HINDI = Value(22, "hi")
  val CROATIAN = Value(23, "hr")
  val HUNGARIAN = Value(24, "hu")
  val INDONESIAN = Value(25, "id")
  val ICELANDIC = Value(26, "is")
  val ITALIAN = Value(27, "it")
  val JAPANESE = Value(28, "ja")
  val KOREAN = Value(29, "ko")
  val KANNADA = Value(30, "kn")
  val LUXEMBOURGISH = Value(31, "lb")
  val LATVIAN = Value(32, "lv")
  val LITUANIAN = Value(33, "lt")
  val MACEDONIAN = Value(34, "mk")
  val MARATHI = Value(35, "mr")
  val MALAY = Value(36, "ml")
  val DUTCH = Value(37, "nl")
  val NORVEGIAN = Value(38, "no")
  val NORVEGIAN_NYNORSK = Value(39, "nn")
  val NORVEGIAN_BOKMAL = Value(40, "nb")
  val NEPALI = Value(41, "ne")
  val POLISH = Value(42, "pl")
  val PORTUGUESE = Value(43, "pt")
  val PUNJABI = Value(44, "pa")
  val ROMANIAN = Value(45, "ro")
  val RUSSIAN = Value(46, "ru")
  val SLOVAK = Value(47, "sk")
  val SLOVENIAN = Value(48, "sl")
  val SERBIAN = Value(49, "sr")
  val SOMALI = Value(50, "so")
  val ALBANIAN = Value(51, "sq")
  val SWEDISH = Value(52, "sv")
  val SWAHILI = Value(53, "sw")
  val TAGALOG = Value(54, "tl")
  val TAMIL = Value(55, "ta")
  val TELEGU = Value(56, "te")
  val TURKISH = Value(57, "tr")
  val THAI = Value(58, "th")
  val UKRAINIAN = Value(59, "uk")
  val URDU = Value(60, "ud")
  val VIETNAMESE = Value(61, "vi")
  val TRADITIONAL_CHINESE = Value(62, "zh-tw")
  val SIMPLIFIED_CHINESE = Value(63, "zh-cn")
  val CHINESE = Value(64, "zh")
}